housepwr<-fread("household_power_consumption.txt",skip = "1/2/2007",nrows=10000,sep=";")
housepwr<-subset(housepwr,V1<="2/2/2007")
names(housepwr)<-c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
housepwr$Date<-as.Date(housepwr$Date,format="%d/%m/%Y")
housepwr$Time<-as.POSIXct(paste(housepwr$Date,housepwr$Time),format="%Y-%m-%d %H:%M:%S")

dev.new()
png("plot3.png")
with(housepwr,plot(Time,Sub_metering_1,type="l"))
with(housepwr,lines(Time,Sub_metering_2,col="red",type="l"))
with(housepwr,lines(Time,Sub_metering_3,col="blue",type="l"))
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=1)
dev.off()